version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/elRed-cicd-app-deployment
hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
